version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli
      # Install sonar-scanner
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
      - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.2.0.1873-linux/bin/
      # Get sonar-scanner details
      - sonar-scanner --version
  pre_build:
    commands:
      # Scan and push to sonarqube
      #- sonar-scanner -Dsonar.host.url=https://cloudpricing-sonar-dev.prcp-np.us-east-1.aws.sysco.net/ -Dsonar.verbose=true -Dsonar.projectName=Cloud-PCI-Frontend

  build:
    commands:
      # Run the build command to generate build folder output
      - npm run build:dev && mv build cloud-pci-dev
      - npm run build:exe && mv build cloud-pci-exe
      - npm run build:stg && mv build cloud-pci-stg
      - npm run build:prod && mv build cloud-pci-prod

      # Use AWS CLI to copy the folder to the relevant s3 codebuild buckets
      - aws s3 cp --recursive cloud-pci-dev/ s3://$S3_BUCKET_NON_PROD/Cloud-PCI-FE/dev/build/
      - aws s3 cp --recursive cloud-pci-exe/ s3://$S3_BUCKET_NON_PROD/Cloud-PCI-FE/exe/build/
      - aws s3 cp --recursive cloud-pci-prod/ s3://$S3_BUCKET_PROD/Cloud-PCI-FE/prod/build/ --acl bucket-owner-full-control