export default [{id: "001", name: "Jackson"},
    {id: "002", name: "Atlanta"},
    {id: "003", name: "Jacksonville"},
    {id: "004", name: "Central California"},
    {id: "005", name: "Intermountain"},
    {id: "006", name: "North Texas"},
    {id: "007", name: "Virginia"},
    {id: "008", name: "Northern New England"},
    {id: "009", name: "Pittsburgh"},
    {id: "010", name: "Eastern Maryland"},
    {id: "011", name: "Louisville"},
    {id: "012", name: "Baltimore"},
    {id: "013", name: "Central Texas"},
    {id: "014", name: "Memphis"},
    {id: "015", name: "Cleveland"},
    {id: "016", name: "South Florida"},
    {id: "017", name: "Las Vegas"},
    {id: "018", name: "Baraboo"},
    {id: "019", name: "Cincinnati"},
    {id: "022", name: "Central Florida"},
    {id: "023", name: "New Orleans"},
    {id: "024", name: "Chicago"},
    {id: "025", name: "Albany"},
    {id: "026", name: "Oklahoma"},
    {id: "027", name: "Syracuse"},
    {id: "029", name: "Arkansas"},
    {id: "031", name: "Sacramento"},
    {id: "032", name: "Southeast Florida"},
    {id: "035", name: "Eastern Wisconsin"},
    {id: "036", name: "San Diego"},
    {id: "037", name: "West Coast Florida"},
    {id: "038", name: "Indianapolis"},
    {id: "039", name: "Iowa"},
    {id: "040", name: "Idaho"},
    {id: "043", name: "Montana"},
    {id: "045", name: "Los Angeles"},
    {id: "046", name: "Central Alabama"},
    {id: "047", name: "Minnesota"},
    {id: "048", name: "Charlotte"},
    {id: "049", name: "Arizona"},
    {id: "050", name: "San Francisco"},
    {id: "051", name: "Central Pennsylvania"},
    {id: "052", name: "Portland"},
    {id: "054", name: "Connecticut"},
    {id: "055", name: "Seattle"},
    {id: "056", name: "Boston"},
    {id: "057", name: "Kansas City"},
    {id: "058", name: "Detroit"},
    {id: "059", name: "Denver"},
    {id: "060", name: "Nashville"},
    {id: "061", name: "Lincoln"},
    {id: "064", name: "St. Louis"},
    {id: "066", name: "New Mexico"},
    {id: "067", name: "Houston"},
    {id: "068", name: "Grand Rapids"},
    {id: "073", name: "Hampton Roads"},
    {id: "075", name: "Philadelphia"},
    {id: "076", name: "Metro New York"},
    {id: "078", name: "West Texas"},
    {id: "101", name: "Ventura"},
    {id: "102", name: "Spokane"},
    {id: "134", name: "IFG - Florida"},
    {id: "137", name: "Columbia"},
    {id: "163", name: "Raleigh"},
    {id: "164", name: "Gulf Coast"},
    {id: "194", name: "Central Illinois"},
    {id: "195", name: "North Dakota"},
    {id: "288", name: "Knoxville"},
    {id: "293", name: "East Texas"},
    {id: "306", name: "Long Island"},
    {id: "320", name: "Riverside"},
    {id: "332", name: "Western Minnesota"},
    {id: "335", name: "Bahamas"},
    {id: "344", name: "IFG - Jacksonville"},
    {id: "429", name: "Doerle"},
    {id: "450", name: "Alaska"}
]
