const businessUnits = new Map(
    [
        ["001", {id: "001", name: "Sysco Jackson", shortName: "Jackson"}],
        ["002", {id: "002", name: "Sysco Atlanta", shortName: "Atlanta"}],
        ["003", {id: "003", name: "Sysco Jacksonville", shortName: "Jacksonville"}],
        ["004", {id: "004", name: "Sysco Central California", shortName: "Central California"}],
        ["005", {id: "005", name: "Sysco Intermountain", shortName: "Intermountain"}],
        ["006", {id: "006", name: "Sysco North Texas", shortName: "North Texas"}],
        ["007", {id: "007", name: "Sysco Virginia", shortName: "Virginia"}],
        ["008", {id: "008", name: "Sysco Northern New England", shortName: "Northern New England"}],
        ["009", {id: "009", name: "Sysco Pittsburgh", shortName: "Pittsburgh"}],
        ["010", {id: "010", name: "Sysco Eastern Maryland", shortName: "Eastern Maryland"}],
        ["011", {id: "011", name: "Sysco Louisville", shortName: "Louisville"}],
        ["012", {id: "012", name: "Sysco Baltimore", shortName: "Baltimore"}],
        ["013", {id: "013", name: "Sysco Central Texas", shortName: "Central Texas"}],
        ["014", {id: "014", name: "Sysco Memphis", shortName: "Memphis"}],
        ["015", {id: "015", name: "Sysco Cleveland", shortName: "Cleveland"}],
        ["016", {id: "016", name: "Sysco South Florida", shortName: "South Florida"}],
        ["017", {id: "017", name: "Sysco Las Vegas", shortName: "Las Vegas"}],
        ["018", {id: "018", name: "Sysco Baraboo", shortName: "Baraboo"}],
        ["019", {id: "019", name: "Sysco Cincinnati", shortName: "Cincinnati"}],
        ["022", {id: "022", name: "Sysco Central Florida", shortName: "Central Florida"}],
        ["023", {id: "023", name: "Sysco New Orleans", shortName: "New Orleans"}],
        ["024", {id: "024", name: "Sysco Chicago", shortName: "Chicago"}],
        ["025", {id: "025", name: "Sysco Albany", shortName: "Albany"}],
        ["026", {id: "026", name: "Sysco Oklahoma", shortName: "Oklahoma"}],
        ["027", {id: "027", name: "Sysco Syracuse", shortName: "Syracuse"}],
        ["029", {id: "029", name: "Sysco Arkansas", shortName: "Arkansas"}],
        ["031", {id: "031", name: "Sysco Sacramento", shortName: "Sacramento"}],
        ["032", {id: "032", name: "Sysco Southeast Florida", shortName: "Southeast Florida"}],
        ["035", {id: "035", name: "Sysco Eastern Wisconsin", shortName: "Eastern Wisconsin"}],
        ["036", {id: "036", name: "Sysco San Diego", shortName: "San Diego"}],
        ["037", {id: "037", name: "Sysco West Coast Florida", shortName: "West Coast Florida"}],
        ["038", {id: "038", name: "Sysco Indianapolis", shortName: "Indianapolis"}],
        ["039", {id: "039", name: "Sysco Iowa", shortName: "Iowa"}],
        ["040", {id: "040", name: "Sysco Idaho", shortName: "Idaho"}],
        ["043", {id: "043", name: "Sysco Montana", shortName: "Montana"}],
        ["045", {id: "045", name: "Sysco Los Angeles", shortName: "Los Angeles"}],
        ["046", {id: "046", name: "Sysco Central Alabama", shortName: "Central Alabama"}],
        ["047", {id: "047", name: "Sysco Minnesota", shortName: "Minnesota"}],
        ["048", {id: "048", name: "Sysco Charlotte", shortName: "Charlotte"}],
        ["049", {id: "049", name: "Sysco Arizona", shortName: "Arizona"}],
        ["050", {id: "050", name: "Sysco San Francisco", shortName: "San Francisco"}],
        ["051", {id: "051", name: "Sysco Central Pennsylvania", shortName: "Central Pennsylvania"}],
        ["052", {id: "052", name: "Sysco Portland", shortName: "Portland"}],
        ["054", {id: "054", name: "Sysco Connecticut", shortName: "Connecticut"}],
        ["055", {id: "055", name: "Sysco Seattle", shortName: "Seattle"}],
        ["056", {id: "056", name: "Sysco Boston", shortName: "Boston"}],
        ["057", {id: "057", name: "Sysco Kansas City", shortName: "Kansas City"}],
        ["058", {id: "058", name: "Sysco Detroit", shortName: "Detroit"}],
        ["059", {id: "059", name: "Sysco Denver", shortName: "Denver"}],
        ["060", {id: "060", name: "Sysco Nashville", shortName: "Nashville"}],
        ["061", {id: "061", name: "Sysco Lincoln", shortName: "Lincoln"}],
        ["064", {id: "064", name: "Sysco St. Louis", shortName: "St. Louis"}],
        ["066", {id: "066", name: "Sysco New Mexico", shortName: "New Mexico"}],
        ["067", {id: "067", name: "Sysco Houston", shortName: "Houston"}],
        ["068", {id: "068", name: "Sysco Grand Rapids", shortName: "Grand Rapids"}],
        ["073", {id: "073", name: "Sysco Hampton Roads", shortName: "Hampton Roads"}],
        ["075", {id: "075", name: "Sysco Philadelphia", shortName: "Philadelphia"}],
        ["076", {id: "076", name: "Sysco Metro New York", shortName: "Metro New York"}],
        ["078", {id: "078", name: "Sysco West Texas", shortName: "West Texas"}],
        ["101", {id: "101", name: "Sysco Ventura", shortName: "Ventura"}],
        ["102", {id: "102", name: "Sysco Spokane", shortName: "Spokane"}],
        ["134", {id: "134", name: "Sysco IFG - Florida", shortName: "IFG - Florida"}],
        ["137", {id: "137", name: "Sysco Columbia", shortName: "Columbia"}],
        ["163", {id: "163", name: "Sysco Raleigh", shortName: "Raleigh"}],
        ["164", {id: "164", name: "Sysco Gulf Coast", shortName: "Gulf Coast"}],
        ["194", {id: "194", name: "Sysco Central Illinois", shortName: "Central Illinois"}],
        ["195", {id: "195", name: "Sysco North Dakota", shortName: "North Dakota"}],
        ["288", {id: "288", name: "Sysco Knoxville", shortName: "Knoxville"}],
        ["293", {id: "293", name: "Sysco East Texas", shortName: "East Texas"}],
        ["306", {id: "306", name: "Sysco Long Island", shortName: "Long Island"}],
        ["320", {id: "320", name: "Sysco Riverside", shortName: "Riverside"}],
        ["332", {id: "332", name: "Sysco Western Minnesota", shortName: "Western Minnesota"}],
        ["335", {id: "335", name: "Sysco Bahamas", shortName: "Bahamas"}],
        ["344", {id: "344", name: "Sysco IFG - Jacksonville", shortName: "IFG - Jacksonville"}],
        ["429", {id: "429", name: "Sysco Doerle", shortName: "Doerle"}],
        ["450", {id: "450", name: "Sysco Alaska", shortName: "Alaska"}]
    ]);

export default businessUnits;
