export const REVIEW_RESULT_TABLE_PAGE_SIZE = 4;
export const REVIEW_REFERENCE_RESULT_TABLE_PAGE_SIZE = 10;
export const PZ_CHANGE_REQUEST_STATUS_PENDING_APPROVAL = 'PENDING_APPROVAL';
export const PZ_DISPLAY_DATE_FORMAT = 'DD MMM YYYY';
export const CIPZ_API_DATE_FORMAT = 'YYYYMMDD';
